# Generated by Django 3.2.8 on 2021-10-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countyname', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthfacilityname', models.CharField(max_length=100)),
                ('noofsuccessfulbirths', models.IntegerField()),
                ('nooflivebirths', models.IntegerField()),
                ('noofstillbirths', models.IntegerField()),
                ('dateentered', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deliveries Table',
                'verbose_name_plural': 'Deliveries Table',
            },
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcountyname', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapapp.county')),
            ],
            options={
                'verbose_name': 'Subcounty',
                'verbose_name_plural': 'Subcounties',
            },
        ),
        migrations.CreateModel(
            name='MaternalDeaths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemorrhage', models.IntegerField(default=0)),
                ('infections', models.IntegerField(default=0)),
                ('hypertension', models.IntegerField(default=0)),
                ('delivery_complication', models.IntegerField(default=0)),
                ('unsafe_abortions', models.IntegerField(default=0)),
                ('deliveries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapapp.deliveries')),
            ],
        ),
        migrations.AddField(
            model_name='deliveries',
            name='subcountyname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapapp.subcounty'),
        ),
    ]
