# Generated by Django 3.2.8 on 2021-10-24 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dapapp', '0002_alter_deliveries_healthfacilityname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveriesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noofsuccessfulbirths', models.IntegerField()),
                ('nooflivebirths', models.IntegerField()),
                ('noofstillbirths', models.IntegerField()),
                ('dateentered', models.DateField(auto_now_add=True)),
                ('facilityname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subcountyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapapp.subcounty')),
            ],
            options={
                'verbose_name': 'DeliveriesInfo Table',
                'verbose_name_plural': 'DeliveriesInfo Table',
            },
        ),
        migrations.CreateModel(
            name='MaternalDeathsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemorrhage', models.IntegerField(default=0)),
                ('infections', models.IntegerField(default=0)),
                ('hypertension', models.IntegerField(default=0)),
                ('delivery_complication', models.IntegerField(default=0)),
                ('unsafe_abortions', models.IntegerField(default=0)),
                ('deliveries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapapp.deliveriesinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='maternaldeaths',
            name='deliveries',
        ),
        migrations.DeleteModel(
            name='Deliveries',
        ),
        migrations.DeleteModel(
            name='MaternalDeaths',
        ),
    ]
